#!/usr/bin/env python3
"""Turns the Android app's strings.xml into the iOS app's Localizable.strings.

The copy is the same product in both apps, so it is translated once and kept in
one place: android/app/src/main/res/values*/strings.xml. Re-run this after
changing a string there.

    python3 ios/tools/strings_from_android.py

Two things are rewritten on the way across:

* `%1$s` becomes `%1$@`. Java's format takes any object for `%s`; iOS wants
  `%@` for an object and keeps `%d` for a number, which is why only the string
  specifier changes.
* Android's escaping is undone and Foundation's applied. Android escapes an
  apostrophe and wraps a string in double quotes to protect leading or trailing
  spaces; .strings needs neither, and needs its own quotes and backslashes
  escaped instead.
"""

from __future__ import annotations

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ANDROID = ROOT / "android/app/src/main/res"
IOS = ROOT / "ios/Mynah/Resources"

# Android locale directory -> iOS .lproj directory.
LOCALES = {"values": "en", "values-zh": "zh-Hans"}


def unescape_android(text: str) -> str:
    """Android's own escaping, undone. XML entities are already gone by here."""
    # A whole string wrapped in double quotes keeps its leading and trailing
    # spaces; the quotes themselves are not part of it.
    if len(text) >= 2 and text.startswith('"') and text.endswith('"'):
        text = text[1:-1]
    out = []
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "\\" and i + 1 < len(text):
            nxt = text[i + 1]
            out.append({"n": "\n", "t": "\t", "'": "'", '"': '"', "@": "@", "\\": "\\"}.get(nxt, nxt))
            i += 2
            continue
        out.append(ch)
        i += 1
    return "".join(out)


def escape_strings(text: str) -> str:
    """Foundation's .strings escaping."""
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def convert_format(text: str) -> str:
    """`%1$s` -> `%1$@`. `%d` and `%%` mean the same thing on both platforms."""
    text = re.sub(r"%(\d+\$)s", r"%\1@", text)
    return re.sub(r"%s", "%@", text)


def read(path: Path) -> dict[str, str]:
    root = ET.parse(path).getroot()
    entries: dict[str, str] = {}
    for element in root:
        if element.tag != "string":
            raise SystemExit(f"{path}: unsupported resource <{element.tag}> — this script only does <string>")
        if list(element):
            raise SystemExit(f"{path}: {element.get('name')} carries inline markup, which .strings cannot")
        entries[element.get("name")] = convert_format(unescape_android(element.text or ""))
    return entries


def main() -> int:
    english = read(ANDROID / "values/strings.xml")

    for source, lproj in LOCALES.items():
        entries = read(ANDROID / source / "strings.xml")
        # A locale that never translated a string falls back to the English one
        # rather than to its key — iOS looks in one bundle only, so the fallback
        # has to be written in rather than inherited.
        missing = [k for k in english if k not in entries]
        merged = {k: entries.get(k, english[k]) for k in english}

        target = IOS / f"{lproj}.lproj/Localizable.strings"
        target.parent.mkdir(parents=True, exist_ok=True)
        lines = [
            "/* Generated by ios/tools/strings_from_android.py — do not edit.",
            f"   Source: android/app/src/main/res/{source}/strings.xml */",
            "",
        ]
        for key, value in merged.items():
            lines.append(f'"{key}" = "{escape_strings(value)}";')
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"{target.relative_to(ROOT)}: {len(merged)} strings"
              + (f", {len(missing)} fell back to English" if missing else ""))

    return 0


if __name__ == "__main__":
    sys.exit(main())
